### ISSUE TITLE
`yarn package` not working 

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#103]
Rollup is failing. Looks like a missing config file? Help / pointers would be most appreciated. 

```(base) jim@BIGDROP:~/projects/onlinewardleymaps$ yarn package
yarn run v1.22.5
$ rollup -c
[!] Error: Could not resolve entry module (rollup.config.js).
Error: Could not resolve entry module (rollup.config.js).
    at error (/home/jim/projects/onlinewardleymaps/node_modules/rollup/dist/shared/rollup.js:5251:30)      
    at ModuleLoader.loadEntryModule (/home/jim/projects/onlinewardleymaps/node_modules/rollup/dist/shared/rollup.js:18410:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by damonsk** [comment]
Hi Jim. Try running Yarn in the wmlandscape folder. I did some work recently to make the core of OWM available as a package for viscose-wardley-maps. Roll up was used to help with this.

**Comment by jimdowning** [comment]
Great, that works to create `dist/index.js` in the wmlandscape folder. How do I get that into the `vscode-wardley-maps` project? And how can I get my vscode working with my local build of the extension, please?

**Comment by damonsk** [comment]
If you remove the wmlandscape package from vscode-wardley-maps and then re-add as a package but with a relative path to your local copy of OWM/wmlandscape that should drag your local changes in.

**Comment by damonsk** [comment]
> How do I get that into the `vscode-wardley-maps` project?

When a pull request gets merged into this repository a new version of wmlandscape will be published to NPM. It's then a case of incrementing the package version in vscode-wardley-maps and publishing a new build of the extension

**Comment by jimdowning** [comment]
Thanks, Damon!

**Comment by jimdowning** [comment]
Reopening this in case you want to edit README.md or improve the build file - I don't have any familiarity with yarn to know what the right solution is.

**Comment by damonsk** [comment]
Info added to readme.

https://github.com/damonsk/onlinewardleymaps/blob/0ca27312b8f592cfa2582dcd1b8d28e92f4ad6c4/README.md?plain=1#L41
