### ISSUE TITLE
component with the word 'marketing' has a problem

### ISSUE THREAD

**Issue by agplusman** [damonsk/onlinewardleymaps#107]
Strangely enough when the component has the word marketing in it then you can't see the link with other components - i have to drop a character like 'mketing' see below
component Sales mrketing [0.21, 0.33]
licensing->disputes
employees->R&d
employees->Sales mrketing

**Comment by demeringo** [comment]
This is a bit funny, but I suspect it may somehow clash with the 'market' object/keyword.
Just a guess without checking the code....

**Comment by damonsk** [comment]
@demeringo - spot on.  Looks like it's this bit of code. 

https://github.com/damonsk/onlinewardleymaps/blob/4f7c771ac16ee1e26376bae2a00a13abd3a0b514/src/conversion/LinksExtractionStrategy.js#L113

the same would happen if the component was named Sales ecosystem

Thanks for the issue.  @agplusman @demeringo

**Comment by damonsk** [comment]
Thanks @demeringo
