### ISSUE TITLE
Feature request - Piplines adding items so they align 

### ISSUE THREAD

**Issue by nthbooth-feedr** [damonsk/onlinewardleymaps#136]
I always have a challenge aligning components onto a pipeline. They always end up slightly off and when I scale the map up and down their alignment also changes even when it was perfect to start with. 

Using the is map as an example:
https://github.com/swardley/Research2022/blob/main/construction/construction-alternative-construction
https://pbs.twimg.com/media/FR6fvOcXoAEZslT?format=jpg&name=large 

And focusing on the following part:

```
component construction technologies [0.39, 0.52] label [28, -32]
pipeline construction technologies [0.35, 0.7]
component robotic [0.37, 0.45] label [-9, 25]
component 3D printing [0.37, 0.41] label [-60, 24]

```
I have a suggestion a new component type called pipelinecomponent this would lead to: 

```
component construction technologies [0.39, 0.52] label [28, -32]
pipeline construction technologies [0.35, 0.7]
pipelinecomponent construction technologies, robotic [0.45] label [-9, 25]
pipelinecomponent construction technologies, 3D printing [0.41] label [-60, 24]
```

pipelinecomponent would just take the location on the pipeline rather than taking both the x and y locations much the same way as the pipeline takes it visibility location from the initial component. 

Apart from that these would act like any other component. 
(eg. you would be able to evolve a pipelinecomponent etc etc)

Update the syntax from the first submission I realised it needed the pipeline name in the pipelinecomponent type
pipelinecomponent <pipeline name> <Component name> [<Maturity>} [label......]

**Comment by damonsk** [comment]
working example: https://beta.onlinewardleymaps.com/#703Ni4Dth65U1mJBCf

**Comment by damonsk** [comment]
bug.. The ability to create a square box without the surrounding box seems to have gone. (just a pipeline without options)

**Comment by damonsk** [comment]
now live.
