### ISSUE TITLE
(beta): Find (& Replace) not available 

### ISSUE THREAD

**Issue by Nordtech** [damonsk/onlinewardleymaps#140]
Using Cmd F (Mac) to find string doesn't work. Is Ok in current version and useful so be good to have it back

<img width="878" alt="image" src="https://user-images.githubusercontent.com/57199126/183051012-d96fef29-38aa-4d20-b7cd-b975ac74a4e2.png">

**Comment by tmotyl** [comment]
@Nordtech in which version it does work and in which it doesn't? It's not clear for me when reading your report

**Comment by tmotyl** [comment]
you mean the beta branch?

**Comment by damonsk** [comment]
the commit 94a765a fixes this.
