### ISSUE TITLE
Save / Export SVG

### ISSUE THREAD

**Issue by exaptations** [damonsk/onlinewardleymaps#141]
At some point, the map may need to be edited outside of the tool being able to save/export the SVG canvas would be an idea here.

I've copied the rendered SVG canvas from the DOM into an SVG tool and it works as expected.

**Comment by Tinkerer-** [comment]
I think this would be a nice addon for either the online tool or the VSCode plugin. I also copied out of the DOM, and it worked, but it's a lot of hassle for just getting an SVG file.

**Comment by damonsk** [comment]
Now live.
