### ISSUE TITLE
Y-axis not working anymore

### ISSUE THREAD

**Issue by lsolesen** [damonsk/onlinewardleymaps#169]
It seems something happened to the y-axis - it is not working?

Neither when putting it into the code:

![image](https://github.com/damonsk/onlinewardleymaps/assets/148026/2eb9cbf9-2b8d-4067-8dcc-3af5b9f4d9de)

Or just on a completely new map:

![image](https://github.com/damonsk/onlinewardleymaps/assets/148026/4cc49d34-32a4-4366-a1af-c441cb5450b9)

**Comment by damonsk** [comment]
Hi @lsolesen 

y-axis was removed in commit https://github.com/damonsk/onlinewardleymaps/commit/ac7ca38a3d3cbedb199c17e51288d57d64ab4e48

This was done inline with feedback from Simon, it's documented in this tweet.  https://twitter.com/swardley/status/1523704708082380801
