### ISSUE TITLE
moving into ReactJS

### ISSUE THREAD

**Issue by damonsk** [damonsk/onlinewardleymaps#18]
Migrate the project away from jQuery to React

**Comment by damonsk** [comment]
I've started moving portions over into React.  There will be lost of jquery in places whilst the project is transitioned.

**Comment by jimdowning** [comment]
How can I help, @damonsk ?

**Comment by damonsk** [comment]
Hi @jimdowning 

I've created a couple of new issues: 
- https://github.com/damonsk/onlinewardleymaps/issues/25
- https://github.com/damonsk/onlinewardleymaps/issues/26
- https://github.com/damonsk/onlinewardleymaps/issues/27
