### ISSUE TITLE
Add test coverage to react app

### ISSUE THREAD

**Issue by ShaunBulbrook** [damonsk/onlinewardleymaps#23]
There is currently no coverage in the app. 

It might be an idea to add snapshot tests to the exisiting components. 
I'm not a big fan of snapshot testing, but it will at least give a dev a smell if an update changes something unexpectedly.

**Comment by damonsk** [comment]
I’m completely new to react and testing react. Happy for you to take lead on this and I (and others) adopt going forward. Could you commit an example of how we should approach it?

**Comment by ShaunBulbrook** [comment]
Gladly! :) 
I'll try to get on this tonight, though with the holidays it might be the end of the week.
