### ISSUE TITLE
Shift label position adjustment into syntax

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#35]
Being able to adjust label position is v useful - should be possible in the syntax not just in drag and drop.

**Comment by damonsk** [comment]
A side effect I observe right now that this would remove is when a label is moved and then the map text is updated, the position of the label is reset or applied to a different label.  

Any suggestions on syntax - 

`component Kettle [0.9,0.2] label [10,30]`

label co-ords would be relative to the component rather than maturity/visibility.

```
component Kettle [visibility,maturity]
    label [x, y]
```

```
component Kettle [visibility,maturity]
    label [x, y]
    evolve [maturity]
    inertia
```

**Comment by jimdowning** [comment]
For now I like the first syntax best. I think allowing multiline declarations is a feature request in its own right - feels like it will be necessary at some point but perhaps not yet?

**Comment by ShaunBulbrook** [comment]
I agree with @jimdowning 

Side-note, if we do opt to do multi-line in the future, we will likely need to re-write/update the logic for dragEnd events to write back the new position of an element. - This isn't neccessarily a bad thing, but it might be an idea to do that work first so users don't experience broken behaviours.

**Comment by damonsk** [comment]
this kind of breaks when a component has evolve set.  There are two labels and two components on the map.  

```
title Tea Shop
anchor Business [0.95, 0.63]
anchor Public [0.95, 0.78]
component Cup of Tea [0.79, 0.61] label [-109, 21]
component Cup [0.73, 0.78] label [-109, 21]
component Tea [0.63, 0.81] label [-309, 194]
!!!!! THIS LINE >>>component Kettle [0.50, 0.53] evolve 0.58 label [0.50, 0.53]
```

What comes to mind now is a breaking change 

maybe it would make sense to break evolve from component and make it its own statement.

```
title Tea Shop
anchor Business [0.95, 0.63]
anchor Public [0.95, 0.78]
component Cup of Tea [0.79, 0.61] label [-109, 21]
component Cup [0.73, 0.78] label [-109, 21]
component Tea [0.63, 0.81] label [-309, 194]
component Kettle [0.50, 0.53] 
evolve Kettle 0.58 label [0.50, 0.53]
```

I'll keep pondering on it, but thoughts welcome

**Comment by damonsk** [comment]
To enable the breaking change, when maps are loaded, we can test to see if the syntax is the old syntax and re-write it.  Same applies to mapText copied/pasted into editor.

**Comment by ShaunBulbrook** [comment]
Sounds good, I don't think that this should be that hard to detect and remediate.
However, we might need to revisit if/when future changes are made.
