### ISSUE TITLE
Better error handling in drag and drop of components

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#36]
I've had a couple of situations where I've picked up a component and something has happened meaning that it won't drop, and remains stuck to the pointer. The only way I've managed to get out of this state is to save and reload the map.

Would be better to have some general exception handling that returns the component to its pre-drag position if any exception occurs during drag or drop. 

Repro: 
1. Define a component with `component foo []`
2. Try to drag it
3. Change the definition to `component foo [.8,]`

**Comment by damonsk** [comment]
@jimdowning - see message: https://github.com/damonsk/onlinewardleymaps/commit/59bb8a0bfa5884e226b795658e360a9c618338a4

**Comment by damonsk** [comment]
Fixed in [59bb8a0](https://github.com/damonsk/onlinewardleymaps/commit/59bb8a0bfa5884e226b795658e360a9c618338a4)
