### ISSUE TITLE
Numbered annotations on areas of the map

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#4]
e.g. https://miro.medium.com/max/2112/1*x5eXd5ylQpQRDHkJ9anrJQ.jpeg

In our mapping we usually annotate components and inertia points, but Simon also annotates floating areas. 
It needs to be possible to use the same annotation target from multiple anchors, for example to illustrate co-evolution of practice. 

Ideally there would be an area to display the annotation expansions too.

**Comment by jimdowning** [comment]
e.g. 
```
annotation 1 ["Standards", "Other Country Standards"] Unilateral adoption of standards would help to overcome inertia.
annotation 2 ["Shareholders", "Global supply chains"] Reducing waste benefits shareholders.
```

**Comment by damonsk** [comment]
starting to flesh this out - test map: http://onlinewardleymaps.com/#HRLQLVSyviChjXxjjZ

Some things

- require x/y for the annotation to be able to position it.  
`annotation 2 [0.82, 0.27] "some text"`
- might need to position the text that is attributed to an annotation.  need relative x/y for the text.
`annotation 2 [0.82, 0.27] "some text" [10, 15]`
- annotations may need to be unique - to be able to mutate the map text if the element is moved via the map, need to be able to reference the annotation

**Comment by jimdowning** [comment]
I think this really needs a) to be able to separate the annotation keys from the text and b) have multiple keys for each annotation. So if you need to position everything manually perhaps for this map 
![20191224_090206](https://user-images.githubusercontent.com/109116/71405203-a791fb00-262c-11ea-803e-2dfb7d87822a.jpg)
the syntax would be something like: -
```
component Hot Water [.6 .78]
component Kettle [.4 .3] evolve .55
component Power [.1 .65] evolve .8
annotation 1 [[.38 .4] [.05 .76]] Standardising power allows Kettles to evolve faster
annotation 2  [[.55 .83]] Hot water is obvious and well known
annotations [.98 .02]
```

**Comment by damonsk** [comment]
made some more progress.  I've aligned it to your syntax.  

Example map: http://onlinewardleymaps.com/#NuotBt8uXiQmayVwbn

**Comment by damonsk** [comment]
Any feedback on this before I close it?

**Comment by jimdowning** [comment]
Looks great to me :-) 🙇
