### ISSUE TITLE
FlowValue missing from render.

### ISSUE THREAD

**Issue by damonsk** [damonsk/onlinewardleymaps#40]
https://twitter.com/RadekMaziarka/status/1213430676617416705

I have some problems with the flow with a label. The app draws flow but it doesn't draw text. Am I the only one who have this problem?

**Comment by rmaziarka** [comment]
I think it's still not working:
![image](https://user-images.githubusercontent.com/5219374/72058831-17f97700-32d1-11ea-877e-5ef046b2ce0f.png)
![image](https://user-images.githubusercontent.com/5219374/72058846-1def5800-32d1-11ea-80e0-881864cc3b29.png)

**Comment by damonsk** [comment]
@rmaziarka could you try 
`Start Component+'insert text'<>`

Here is an example.  It's related to future/past/both evolution links - if a component has evolved or not.  

https://onlinewardleymaps.com/#h3OpwFgJzdakzyEC79
