### ISSUE TITLE
Example map fubar

### ISSUE THREAD

**Issue by jimdowning** [damonsk/onlinewardleymaps#42]
Can't work out what's going on, but pressing "Example map" yielded this: 

![image](https://user-images.githubusercontent.com/109116/71778481-6263b680-2fa6-11ea-8afc-29294c4dfdee.png)

**Comment by ShaunBulbrook** [comment]
I'm unable to replicate this on my machine.
Which browser/OS are you using? 

I am concious that I can see a red save button at the moment and can't see one in your screenshot.
Might be something that @damonsk has fixed since this was raised?

**Comment by damonsk** [comment]
Not fixed I added that this morning. 

Looking at the map it has a url. Did you load an existing map then click example map? I’m not near machine to test.

**Comment by damonsk** [comment]
Can recreate by first loading a map then clicking Example Map.  Not sure what is going on to cause this, will need to dig around. @ShaunBulbrook any suggestions what could do this?

**Comment by jimdowning** [comment]
Yes, I think that's the case Damon. I'll try to get a clean repro together
tomorrow.

jim

**Comment by jimdowning** [comment]
Can confirm this is fixed.
