### ISSUE TITLE
Allow changing labels of vertical (Value Chain) Axis.

### ISSUE THREAD

**Issue by markneumann** [damonsk/onlinewardleymaps#46]
You allow changing the evolution axis labels.
Please allow changing the value chain axis labels.

Thanks!

**Comment by damonsk** [comment]
any suggestions on the syntax for this?  For the x-axis we use evolution.

**Comment by markneumann** [comment]
Maybe “value” ?

Mark Neumann

**Comment by jimdowning** [comment]
Suggest: 
```
y-axis-label Value Chain
y-axis-min Invisible
y-axis-max Visible
```

**Comment by markneumann** [comment]
Good point about the major vs minor label
I was thinking:
evolution First->Second->Third->Fourth
value Low -> High

but I don't think people will change the x-axis much, so y-axis needs more flexibility

**Comment by jimdowning** [comment]
Yeah, I don't think we need to worry about the x axis so much. With a label, min and max we have three string fields, so it would have to be something like
```y-axis Some label -> Min label -> Max label```
or
```y-axis Some label = Min label -> Max label```

**Comment by damonsk** [comment]
I have built this in using 

`y-axis Custom Label->Min->Max` syntax.

Example Map: https://onlinewardleymaps.com/#dVLtp1rttBmNYldQwX

In build 1.120
