### ISSUE TITLE
Add "anchor" variable

### ISSUE THREAD

**Issue by c0rdis** [damonsk/onlinewardleymaps#52]
Since all the maps should start with user needs, it may be a good idea to add a new variable "anchor" which would be somewhat different from the standard "component" and clearly show where everything starts.

**Comment by damonsk** [comment]
thanks @c0rdis, i have made this change.

Example map:  https://onlinewardleymaps.com/#GGlqOsptGGGYJQbb14 

`title Tea Shop
anchor Business [0.95, 0.63]
anchor Public [0.95, 0.78]
component Cup of Tea [0.79, 0.61]
component Cup [0.73, 0.78]

Business->Cup of Tea
Public->Cup of Tea
Cup of Tea->Cup
style colour`
