### ISSUE TITLE
Grammar to render pipelines

### ISSUE THREAD

**Issue by jhngrant** [damonsk/onlinewardleymaps#63]
Would it be possible to extend the grammar to render pipelines?

Perhaps the semantics could be similar to evolve

`evolve Name (X Axis)`

A pipeline could be defined as

`pipeline Name [X Axis, X Axis]`

After exporting a PNG of the following map. I used a graphics editor to overlay the pipelines. It would be so useful to script these instead:
```
title Evolution of Work
style wardley

anchor Business [0.95, 0.28]

component Human Capital [0.84, 0.23] label [-95, -10]
component Capital [0.85, 0.33] label [4, -9]
component Automation [0.29, 0.50] label [2, -10]
component Systematization [0.45, 0.24] label [-94, -16]
component Craft [0.67, 0.21] label [-41, -9]
component AI [0.07, 0.55] label [2, -10]

Business->Human Capital
Business->Capital
Human Capital->Craft
Craft->Systematization
Capital->Automation
Systematization->AI
Automation->AI
```

![Evolution-of-Work](https://user-images.githubusercontent.com/5324735/80115833-2405fd80-857d-11ea-8895-741eb728d54a.png)

**Comment by damonsk** [comment]
Foundations are in place, still some functionality missing like drag/drop/moving and also the nice to have highlighting.  Let me know how it works for you, any feedback.  Thanks

Using your example with the additional pipeline - https://onlinewardleymaps.com/#clone:S1TGvJwDHevkZew7Nv

**Comment by jhngrant** [comment]
Very nice!

One observation, when `style colour` the arrowhead disappears.

This is more a nice to have, but swardley uses a square, rather than a circle, to represent a pipeline component. For example (note the transparent background of the rectangle and arrowhead position is slightly wrong here):

![image](https://user-images.githubusercontent.com/5324735/80272868-3723e500-86c5-11ea-997b-1bf4b0525c33.png)
Source: https://twitter.com/swardley/status/1246111821653737472

With this convention the evolution aspect could become optional by setting the extents to zero: 

`pipeline Name [0, 0]`

For example:

![image](https://user-images.githubusercontent.com/5324735/80272881-56bb0d80-86c5-11ea-867c-a5bff02db0ed.png)
Source: https://twitter.com/swardley/status/1147506180450934784

**Comment by damonsk** [comment]
Thanks for the input @jhngrant appreciated it.  I have pushed in some changes which should address the points you've raised. As always, feedback welcome.

**Comment by damonsk** [comment]
The pipeline points can now be dragged/dropped from either end.

**Comment by jhngrant** [comment]
Fantastic. Thanks you.
