### ISSUE TITLE
Grammar to link submaps

### ISSUE THREAD

**Issue by jhngrant** [damonsk/onlinewardleymaps#65]
Would it be possible to extend the grammar to support submaps?

Clicking a submap component would navigate to the specified address of a lower level map.

```
submap Name [Y, X] VarName

var Name Value
```

The convention used in Atlas is a component with a solid fill:

![components](https://user-images.githubusercontent.com/5324735/80753845-df9ed280-8b25-11ea-85ca-d3dd30286a0d.png)

Example script:
```
submap Order Pipeline [0.8, 0.6] OrderPipelineMap

var OrderPipelineMap "https://onlinewardleymaps.com/#clone:zYTNMRLQKvdbVFVNGi"
```

**Comment by damonsk** [comment]
```
submap Order Pipeline [0.8, 0.6] url(OrderPipelineMap)

url OrderPipelineMap [https://onlinewardleymaps.com/#clone:zYTNMRLQKvdbVFVNGi]
```

Hi John, this is pretty much live now - did some tweaks around the syntax.  How does this look?

Example: https://onlinewardleymaps.com/#clone:qu4VDDQryoZEnuw0ZZ

**Comment by jhngrant** [comment]
Thank you. Great work.
