### ISSUE TITLE
When navigating away from the page with unsaved work, prompt

### ISSUE THREAD

**Issue by damonsk** [damonsk/onlinewardleymaps#73]
As title - to prevent accidentally losing work, like I've just done.. :(

**Comment by ChristianDavis** [comment]
The check on navigate is a good feature and might be important, but I would suggest implementing a localStorage autosave/rehydrate first. It's pretty simple to get in and would probably cover that case without dealing with a prompt. Adds a bit of complexity to saving and reloading from the server, or opening maps in multiple tabs, but I think with what you got it's minor.

I can share some code if that's of interest

**Comment by damonsk** [comment]
That sounds even better code would be appreciated 👍

**Comment by tmotyl** [comment]
I know I'm late to the party, but I also lost my work today. @ChristianDavis would you mind sending a PR?

**Comment by damonsk** [comment]
Completed.
