### ISSUE TITLE
Allow comments in script

### ISSUE THREAD

**Issue by modernist** [damonsk/onlinewardleymaps#83]
It would be useful to be able to leave comments in the script that is used to generate the map, e.g. by starting the line with a '#' symbol, especially in larger maps with many components and areas.

I'd be happy to provide help with implementing such a feature.

**Comment by jhngrant** [comment]
`
// Single line comments
`

```
/*

Block comments

*/
```

https://docs.onlinewardleymaps.com/2020-06-06/tips-tricks-using-notes
