### ISSUE TITLE
Pioneers, Settlers, Townplanners area does not scale as the map scales. 

### ISSUE THREAD

**Issue by nthbooth** [damonsk/onlinewardleymaps#88]
The current Pioneers, Settlers, Townplanners area does not scale as the map scales as the browser is resized. 

The current implementation of Pioneers, Settlers, Townplanners area uses the following: 

pioneers visibility, maturity width height

My suggestion would be that it is changed to the following:

pioneers start visibility, start maturity, end visibility, end maturity width height 

Leaving width height allows for backward compatibility with current maps. 

If the end visibility and end maturity were in place the width and height would be ignored. 

End visibility/maturity may be the wrong name but it allows for a dynamically sized box that will adapt the browser size rather than being a fixed height and width. 

Nick
Example:
Both of the following were created with the same map: 
pioneers [0.95, 0.02] 450 1030
settlers [0.95, 0.44] 250 1030
townplanners [0.95, 0.75] 250 1030

note Pioneers [0.03, 0.38]
note Settlers [0.03, 0.62]
note Town Planners [0.03, 0.90]

![image](https://user-images.githubusercontent.com/21123527/95617653-ae76e680-0a63-11eb-8e90-46dab558a5c8.png)

![image](https://user-images.githubusercontent.com/21123527/95617704-c0588980-0a63-11eb-8096-98d6212619e0.png)

**Comment by damonsk** [comment]
Thanks for this Nick.  I've had to change it quite a lot and have decided not to maintain backwards capability.  Instead I have implemented a migration script which will update maps with a best guess if they're loaded with the old syntax. 


```pioneers [0.95, 0.02, 0.75, 0.22]
settlers [0.95, 0.44, 0.75, 0.64]
townplanners [0.95, 0.75, 0.75, 0.95]
```

```
(pioneers|settlers|townplanners) [<visibility>, <maturity>, <visibility2>, <maturity2>]
```

**Comment by HonzaMac** [comment]
Thank you for your work!

**Comment by nthbooth** [comment]
This is awesome thank you!
