### ISSUE TITLE
evolving and build, buy and outsource

### ISSUE THREAD

**Issue by nthbooth** [damonsk/onlinewardleymaps#89]
In my quest to improve my map I have now been playing with build, buy and outsource. 
Example: https://onlinewardleymaps.com/#wMrpVBDGR0IiyY9yjb 
anchor Customer [0.99,0.5]
Customer->Happiness
buy Happiness
component Happiness [0.8,0.5] inertia
evolve Happiness 0.9

I originally was thinking that it was a bug that the "buy" was not shown on the evolved component but in retrospect and thinking about what happens during the evolution I think it is more than the future state needs a different method. 

so maybe something like the following is needed: 
buy Happiness 
evolve Happiness 0.9 
outsource evolved_Happiness 

Or maybe I am just missing something and this is not actually a thing.

![image](https://user-images.githubusercontent.com/21123527/95664609-734ae500-0b41-11eb-8d4c-3e22f4b432da.png)

**Comment by damonsk** [comment]
Heres some changes... 
```
title annoying example
anchor Customer [0.99,0.5]
Customer->Happiness
buy Happiness
component Happiness [0.80, 0.26] inertia
evolve Happiness 0.9 (build)

component Foo [0.57, 0.11] (build) 
evolve Foo 0.8 (buy) 

component AppStore [0.39, 0.52]
evolve AppStore 0.75 (market)
```

you can now decorate wrapping the type in ()

for example: 

```component Foo [0.9, 0.75] (buy)
evolve Foo 0.9 (outsource)
```

I updated your map with the changes: https://onlinewardleymaps.com/#wMrpVBDGR0IiyY9yjb

![image](https://user-images.githubusercontent.com/709078/95678409-5d323880-0bc4-11eb-9e52-004bbc7a13ba.png)
