### ISSUE TITLE
Bug: notes don't seem to save their location when moved on the map with the cursor 

### ISSUE THREAD

**Issue by nthbooth** [damonsk/onlinewardleymaps#91]
When there is a comment above using // when moving the note in the diagram (using the cursor) it does not save where the note has been moved to. 

Other items on the map move and save their location without issue it only seems to be a problem with note and only once a // comment has been added above. removing the // comment does not fix the issue.

For example, try moving "Key" in the following example: 

https://onlinewardleymaps.com/#wMrpVBDGR0IiyY9yjb

**Comment by damonsk** [comment]
Closing this as the issue appears fixed.
