### ISSUE TITLE
Bug: Another inertia issue

### ISSUE THREAD

**Issue by nthbooth** [damonsk/onlinewardleymaps#94]
When there is no evolution stated you can still have inertia showing on the map. 

example: 

component another issue inertia [0.5, 0.39]  inertia 

![image](https://user-images.githubusercontent.com/21123527/95771725-71089800-0cb3-11eb-9a24-26957ba03896.png)

**Comment by damonsk** [comment]
This is where my knowledge starts to fail me in mapping. #50 was to implement this functionality.

**Comment by nthbooth** [comment]
Ok I had not seen this before but with that context it makes sense!  Not a bug actually a feature.
